import Head from 'next/head'
import Image from 'next/image'
import { GetStaticProps } from "next";
import styles from '../styles/Home.module.css'
import { fetchWooCommerceProducts } from '../utils/fetchProducts';
import styled from "styled-components"
import ProductGrid from "../components/ProductGrid";


export default function Home(props) {

  const { products } = props;


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ProductGrid products={products} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getStaticProps = async () => {
  const WooCommerceProducts = await fetchWooCommerceProducts().catch((err) => console.log(err));

  if (!WooCommerceProducts){
    return {
      notFound: true
    };
  }

  return {
    props: {
      products: WooCommerceProducts.data
    }
  }
}
